name: "PacketAnalyzer"
version: "1.2"
main: "net.toshimichi.packetanalyzer.Main"
commands:
  frame:
    usage: "/frame"
    description: "Shows packet analyse window"
    permission: "packetanalyzer.frame"
  monitor:
    usage: "/monitor <player>"
    description: "Starts/stops packet capturing"
    permission: "packetanalyzer.monitor"